name: NPM Publish

on:
  push:
    branches:
      - master
    paths:
      - 'frontend/**'
  pull_request:
  workflow_dispatch:

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1.4.4
        with:
          node-version: 15
          registry-url: https://npm.pkg.github.com/
      - name: Build
        run: |
          npm ci
          npm run build
        working-directory: frontend
      - name: Test
        run: |
          npm ci
          npm run test
        working-directory: frontend
      - name: Publish
        if: (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/master'
        run: |
          npm version prerelease -preid ${GITHUB_SHA} -no-git-tag-version
          npm publish
        working-directory: frontend
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
